// The Bazaar — a short run of independent stall-fronts linking the Dockside
// Retail service corridor (west) to the Industrial Sector accessway (east/north).
// Reached ON FOOT only: it is NOT a TravelTube stop. Built from maps/bazaar.yaml
// via buildAreaFromYaml.
//
// Topology note: the mapper's bazaar.yaml opens with a placeholder
// `horizon_corridor` room standing in for the EXISTING Dockside Retail service
// corridor (built in horizon.ts). We do NOT rebuild that room here — instead the
// real corridor gains an east exit into the bazaar (wired in horizon.ts), and the
// placeholder is dropped from the inlined YAML below. The clothing vendor's
// `west` exit resolves straight onto the real corridor.
//
// Descriptions are placeholder/starter prose — enough to read coherently while
// the bazaar's content (vendors, wares, any NPCs) is filled in later.
import { buildAreaFromYaml } from "./area.js";
// The mapper's bazaar.yaml, minus the placeholder `horizon_corridor` room (see
// the header note). `stop: null` — the bazaar is foot-traffic only.
const BAZAAR_YAML = `
# Generated by tools/mapper.html
area: bazaar
areaName: "Bazaar"
stop: null
rooms:
  - id: horizon_clothing_vendor
    name: "Clothing vendor"
    exits:
      east: horizon_drinks_vendor
      west: horizon_corridor
  - id: horizon_drinks_vendor
    name: "Drinks vendor"
    exits:
      east: horizon_doughnut_vendor
      west: horizon_clothing_vendor
  - id: horizon_doughnut_vendor
    name: "Doughnut vendor"
    exits:
      east: horizon_hot_dog_vendor
      west: horizon_drinks_vendor
  - id: horizon_hot_dog_vendor
    name: "Hot dog vendor"
    exits:
      east: horizon_corridor2
      west: horizon_doughnut_vendor
  - id: horizon_corridor2
    name: "Corridor"
    exits:
      east: horizon_traveltube_pod_maintenance_area
      west: horizon_hot_dog_vendor
  - id: horizon_traveltube_pod_maintenance_area
    name: "TravelTube pod maintenance area"
    exits:
      north: horizon_industrial_sector_accessway
      west: horizon_corridor2
  - id: horizon_industrial_sector_accessway
    name: "Industrial sector accessway"
    exits:
      south: horizon_traveltube_pod_maintenance_area
`;
const STALL = "One of the Bazaar's independent stall-fronts, wedged into the run of " +
    "shopfronts between the retail concourse and the station's working quarter. " +
    "Wares are stacked high and the trader behind the counter watches the passing " +
    "trade with a practised eye. The Bazaar continues east and west.";
const CORRIDOR = "A plain connecting corridor along the spine of the Bazaar, the stall-fronts " +
    "giving way to bare wall. It runs on in either direction.";
// Per-stall starter prose, keyed by room id. Plain placeholders for now — the
// actual goods, prices and any vendor NPCs come later.
const STALLS = {
    horizon_clothing_vendor: "A clothing stall hung with racks of practical station wear and a few " +
        "louder pieces angled at travellers with credits to burn. The Bazaar " +
        "continues east; west, the Dockside Retail service corridor leads back " +
        "toward the shops.",
    horizon_drinks_vendor: "A drinks stall — chilled cabinets glowing along the back wall, a dispenser " +
        "hissing somewhere out of sight. The Bazaar runs east and west.",
    horizon_doughnut_vendor: "A doughnut stall, the warm smell of frying sugar carrying well past the " +
        "counter. Trays of glazed rings sit under a heat lamp. The Bazaar continues " +
        "east and west.",
    horizon_hot_dog_vendor: "A hot-dog stall, a roller-grill turning its wares under a hand-lettered " +
        "price board. The Bazaar runs east and west.",
};
function bazaarDefault(r) {
    if (STALLS[r.id])
        return STALLS[r.id];
    const n = r.name.toLowerCase();
    if (n.includes("maintenance"))
        return ("A TravelTube pod maintenance area — a half-industrial bay where pods are " +
            "shunted off the line for servicing, oil-stained decking underfoot and the " +
            "smell of warm machinery. The Bazaar is back to the west; an accessway " +
            "leads north toward the Industrial Sector.");
    if (n.includes("accessway"))
        return ("The Industrial Sector accessway: the polish of the public station falls " +
            "away here into bare structural metal and stencilled signage. The " +
            "maintenance bay is back to the south; the Industrial Sector proper lies " +
            "north.");
    if (n.includes("vendor"))
        return STALL;
    return CORRIDOR;
}
// Examinable nouns the stall prose name-drops (so EXAMINE answers them).
const BAZAAR_SCENERY = {
    horizon_clothing_vendor: {
        racks: "Racks of practical station wear — hard-wearing, unglamorous, sensibly cut — and, jammed in among them, a few louder pieces for travellers keen to look like they're somewhere.",
        clothing: "Practical wear, mostly, with a scatter of louder pieces. Nothing you need; nothing priced for someone watching their credits.",
        wear: "Practical wear, mostly, with a scatter of louder pieces. Nothing you need; nothing priced for someone watching their credits.",
        counter: "A counter heaped with folded stock, the trader behind it pricing up the passing trade with a practised eye.",
    },
    horizon_drinks_vendor: {
        cabinet: "Chilled cabinets glow along the back wall, ranked with bottles and cans beaded with cold.",
        cabinets: "Chilled cabinets glow along the back wall, ranked with bottles and cans beaded with cold.",
        dispenser: "A drinks dispenser hisses somewhere out of sight, ready to fill a cup with whatever lurid thing you point at.",
    },
    horizon_doughnut_vendor: {
        doughnuts: "Trays of glazed rings sit under a heat lamp, the sugar catching the light. The smell does most of the selling.",
        trays: "Trays of glazed rings under a heat lamp, restocked the moment they thin out.",
        lamp: "A heat lamp keeps the doughnuts warm and the smell aggressive. It is, commercially, doing God's work.",
    },
    horizon_hot_dog_vendor: {
        grill: "A roller-grill turns a row of glistening sausages back and forth, in no hurry and never quite stopping.",
        board: "A hand-lettered price board, the numbers rubbed and re-chalked more than once. Cheap, and proud of it.",
        sign: "A hand-lettered price board, the numbers rubbed and re-chalked more than once. Cheap, and proud of it.",
    },
    horizon_traveltube_pod_maintenance_area: {
        pods: "A couple of TravelTube pods sit shunted off the line, panels open, the innards that whisk you about the station laid bare and a good deal less magical up close.",
        pod: "A TravelTube pod up on the servicing deck, one panel off — surprisingly ordinary machinery for something that feels like teleportation.",
        decking: "Oil-stained decking, scuffed by decades of pods being shunted on and off the line.",
    },
    horizon_industrial_sector_accessway: {
        signage: "Stencilled signage in functional yellow and black — hazard markings, directions, the curt grammar of a place that expects you to know where you're going.",
        metal: "Bare structural metal, unpolished and honest, where the public station's gloss gives out.",
    },
};
const built = buildAreaFromYaml(BAZAAR_YAML, {
    defaultDescription: bazaarDefault,
    rooms: Object.fromEntries(Object.entries(BAZAAR_SCENERY).map(([id, scenery]) => [id, { scenery }])),
});
// Cross-area, on-foot link north into the Industrial Sector (the Industrial side
// of this link — horizon_narrow_corridor's reciprocal south — is wired in
// industrial.ts). The mapper drops cross-area exits, so we add it by hand.
built.rooms["horizon_industrial_sector_accessway"].exits.north =
    { to: "horizon_narrow_corridor", description: "the Industrial Sector" };
export const bazaarRooms = built.rooms;
