// Celestial Dining Area (CANON) — Horizon Outpost's refined, polished-stone
// dining zone, a world away from the bustle elsewhere. Built from
// maps/celestial_dining.yaml via buildAreaFromYaml.
//
// Layout: a two-part Dining Concourse with FOUR upscale units arranged around it
// (canon: "four retail units… tables and chairs out front, indoor seating
// within"), and — around a quiet corner, tucked slightly apart — the modest,
// canon-important Burrito Céleste. 'Tube-only — the arrival (cda_tube_stop) is a
// TravelTube stop declared in its index.ts MODULES entry (reader_cda).
//
// CANON vs invented: Burrito Céleste (cda_burrito) and the zone's overall
// character are canon. The four named units (The Orrery / Saffron & Ash / The
// Long Table / Meridian) are INVENTED placeholders — canon leaves them unnamed —
// and can be freely renamed/replaced when the dining content is authored.
// Burrito Céleste's no-nonsense server is canon (Strand 1) but is described in
// prose here, not yet an NPC object.
import { buildAreaFromYaml } from "./area.js";
const CELESTIAL_DINING_YAML = `
# Generated by tools/mapper.html
area: celestial_dining
areaName: "Celestial Dining Area"
stop: cda_tube_stop
rooms:
  - id: cda_tube_stop
    name: "Celestial Dining — Arrival"
    stop: true
    exits:
      south: cda_concourse_n
  - id: cda_concourse_n
    name: "Celestial Dining — Dining Concourse"
    exits:
      north: cda_tube_stop
      east: cda_unit_orrery
      west: cda_unit_saffron
      south: cda_concourse_s
  - id: cda_unit_orrery
    name: "Celestial Dining — The Orrery"
    exits:
      west: cda_concourse_n
  - id: cda_unit_saffron
    name: "Celestial Dining — Saffron & Ash"
    exits:
      east: cda_concourse_n
  - id: cda_concourse_s
    name: "Celestial Dining — Dining Concourse"
    exits:
      north: cda_concourse_n
      east: cda_unit_long_table
      west: cda_unit_meridian
      south: cda_corner
  - id: cda_unit_long_table
    name: "Celestial Dining — The Long Table"
    exits:
      west: cda_concourse_s
  - id: cda_unit_meridian
    name: "Celestial Dining — Meridian"
    exits:
      east: cda_concourse_s
  - id: cda_corner
    name: "Celestial Dining — Quiet Corner"
    exits:
      north: cda_concourse_s
      east: cda_burrito
  - id: cda_burrito
    name: "Celestial Dining — Burrito Céleste"
    exits:
      west: cda_corner
`;
function cdaDefault(_r) {
    return "A calm, polished-stone corner of the Celestial Dining Area.";
}
function stopDescription(s) {
    return ("The travel-tube doors open and the contrast with the rest of the outpost is " +
        "immediate. This is a calmer, more refined part of the station: the walls " +
        "and floor are clad in polished stone, clean and shining to a degree that " +
        "shames even the best-kept corners of Horizon. The lighting is diffuse and " +
        "warm rather than harsh — bright without glare — and threading through " +
        "everything is gentle music, quiet enough to allow conversation without " +
        "effort. " +
        (s.flags["pod_summoned_at"] === "cda_tube_stop"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        "\n\nThe dining concourse opens up to the south.");
}
const built = buildAreaFromYaml(CELESTIAL_DINING_YAML, {
    defaultDescription: cdaDefault,
    rooms: {
        cda_tube_stop: {
            description: stopDescription,
            items: ["reader_cda"],
        },
        cda_concourse_n: {
            description: "The north end of the dining concourse — polished stone underfoot, warm " +
                "light, low music, and the unhurried murmur of people eating well and in " +
                "no hurry about it. Two of the zone's four anchor units face each other " +
                "here, tables and chairs set out in front of each: The Orrery to the " +
                "east, Saffron & Ash to the west. The travel-tube exit is back north; " +
                "the concourse continues south.",
        },
        cda_concourse_s: {
            description: "The south end of the dining concourse, as calm and considered as the " +
                "rest. The zone's other two anchor units sit here with their outdoor " +
                "tables: The Long Table to the east, Meridian to the west. The concourse " +
                "runs back north; a quieter corner leads off to the south. It is, " +
                "unmistakably, the kind of place that costs a little more than average " +
                "and knows it.",
        },
        cda_unit_orrery: {
            scenery: {
                orrery: "Overhead, a slow brass model of a planetary system turns on near-invisible arms, planets gliding through their orbits above the white linen. It is the kind of detail that tells you the bill before the menu does.",
                tables: "White-linen tables dressed beneath the turning orrery, a few coveted ones spilling out front onto the polished stone.",
                sommelier: "A sommelier who means it moves between the tables, the sort of person who could ruin your evening with one raised eyebrow at your choice of water.",
                dome: "A domed ceiling, the brass orrery wheeling slowly across it, the whole room built to make you forget there's a station outside.",
            },
            description: "The Orrery — the grandest of the four units: a domed dining room where " +
                "a slow brass model of a planetary system turns overhead, white-linen " +
                "tables dressed beneath it. Tasting menus, a sommelier who means it, and " +
                "prices to match the spectacle. A few coveted tables spill out front " +
                "onto the polished stone. The concourse is back west.",
        },
        cda_unit_saffron: {
            scenery: {
                kitchen: "An open-fire kitchen at the back, flames leaping under iron, sending up the scent of charred spice and woodsmoke across the amber-lit room.",
                fire: "Open flames under the kitchen irons, the cooks moving through the heat with the calm of people who do this nightly.",
                tables: "Tables set out front and within, amber-lit and aromatic, every one of them entirely unembarrassed by the bill to come.",
            },
            description: "Saffron & Ash — an open-fire kitchen sending up the scent of charred " +
                "spice and woodsmoke, the dining room warm and amber-lit. Aromatic, " +
                "fashionable, and entirely unembarrassed by the bill. Tables out front; " +
                "the concourse is back east.",
        },
        cda_unit_long_table: {
            scenery: {
                table: "A single great communal table running down the centre of the room, strangers seated elbow to elbow over small, precise, expensive plates. Convivial by careful, costly design.",
                plates: "Small, precise, expensive plates arriving in a steady procession, each one a sentence rather than a meal.",
                strangers: "Strangers elbow to elbow down the long table, performing conviviality at one another over the wine, mostly pulling it off.",
            },
            description: "The Long Table — a single great communal table running down the centre " +
                "of the room, strangers seated elbow to elbow over small, precise, " +
                "expensive plates. Convivial by careful design. Tables out front; the " +
                "concourse is back west.",
        },
        cda_unit_meridian: {
            scenery: {
                bar: "A long, cold marble counter where a bartender builds cocktails with unhurried precision. BUY a COCKTAIL and watch a professional work.",
                counter: "A long counter of pale stone, crushed ice and shellfish on display along it, understated and quietly ruinous.",
                ice: "Crushed ice heaped along the raw bar, shellfish bedded in it, glistening and cold and absurdly expensive.",
                shellfish: "Shellfish on a bed of crushed ice — oysters and the like, displayed the way jewellers display the things you also can't afford.",
                bartender: "A bartender building cocktails with the unhurried precision of someone who has never once been rushed and never will be. BUY a COCKTAIL.",
            },
            description: "Meridian — a cool, pale raw bar: crushed ice, shellfish on display, and " +
                "a long counter where a bartender builds cocktails with unhurried " +
                "precision. Understated, and quietly ruinous. Tables out front; the " +
                "concourse is back east.",
        },
        cda_corner: {
            description: "A quiet corner of the dining zone, set slightly apart from the four " +
                "main units — the polished stone giving way to something cosier, the " +
                "music softer still. Around the corner to the east, a modest frontage " +
                "and an extraordinary smell announce Burrito Céleste. The concourse is " +
                "back north.",
        },
        cda_burrito: {
            npcs: ["celeste_server"],
            scenery: {
                hatch: "A serving hatch, manned by a no-nonsense server, the whole operation about the size of one of the neighbours' wine lists. BUY a BURRITO.",
                tables: "A handful of small tables, most of them occupied by people who clearly know exactly what they came for.",
                table: "A small table, plainly set, the sort you're glad to get because it means the food is close.",
                smell: "The smell alone tells you everything: warm, spiced, extraordinary, and entirely out of keeping with the modest frontage. BUY a BURRITO and find out why people make the trip.",
            },
            description: "Burrito Céleste — modest in its frontage: a serving hatch manned by a " +
                "no-nonsense server, and a handful of small tables, most of them " +
                "occupied. It has none of the grandeur of its neighbours, but the smell " +
                "alone tells you everything you need to know. The food, by all accounts, " +
                "is worth every credit. The quiet corner is back west.",
        },
    },
});
export const celestialDiningRooms = built.rooms;
