// Entertainment Zone 1 — Horizon Outpost's after-dark, adult-oriented nightlife
// district (NON-canon — invented). (Canon's other entertainment district, the
// arcade, is Entertainment Zone 2 — still to map.) Built from
// maps/entertainment_zone_1.yaml via buildAreaFromYaml.
//
// Deliberately EASY to navigate (not labyrinthine): a straight neon Promenade
// running West → Centre → East, with venues opening off each side and a couple
// of back-rooms. 'Tube-only access — the entrance (ez1_tube_stop) is a TravelTube
// stop declared in its index.ts MODULES entry (reader_ez1). No walking link to
// the rest of the outpost.
//
// Tone: tasteful-adult nightlife — drinking, dancing, gambling, cabaret, cigars,
// late-night food, ink. Prose is full starter content; any interactive bits
// (drinks/menus/NPCs, a possible Chas scene if Chas lands here rather than Zone
// 2) come in a later pass.
import { buildAreaFromYaml } from "./area.js";
import { syncBarNpcs } from "./bar_npcs.js";
const ENTERTAINMENT_ZONE_1_YAML = `
# Generated by tools/mapper.html
area: entertainment_zone_1
areaName: "Entertainment Zone 1"
stop: ez1_tube_stop
rooms:
  - id: ez1_tube_stop
    name: "Entertainment Zone 1 — TravelTube Stop"
    stop: true
    exits:
      east: ez1_promenade_w
      south: ez1_cloakroom
  - id: ez1_cloakroom
    name: "Entertainment Zone 1 — Cloakroom & Toilets"
    exits:
      north: ez1_tube_stop
  - id: ez1_promenade_w
    name: "Entertainment Zone 1 — Promenade (West)"
    exits:
      west: ez1_tube_stop
      east: ez1_promenade_c
      north: ez1_brass_rail
      south: ez1_stardust_diner
  - id: ez1_brass_rail
    name: "Entertainment Zone 1 — The Brass Rail"
    exits:
      south: ez1_promenade_w
      east: ez1_long_shot
  - id: ez1_long_shot
    name: "Entertainment Zone 1 — The Long Shot"
    exits:
      west: ez1_brass_rail
  - id: ez1_stardust_diner
    name: "Entertainment Zone 1 — The Stardust Diner"
    exits:
      north: ez1_promenade_w
  - id: ez1_promenade_c
    name: "Entertainment Zone 1 — Promenade (Centre)"
    exits:
      west: ez1_promenade_w
      east: ez1_promenade_e
      north: ez1_eclipse
      south: ez1_long_odds
  - id: ez1_eclipse
    name: "Entertainment Zone 1 — Eclipse"
    exits:
      south: ez1_promenade_c
      north: ez1_eclipse_vip
  - id: ez1_eclipse_vip
    name: "Entertainment Zone 1 — Eclipse VIP Lounge"
    exits:
      south: ez1_eclipse
  - id: ez1_long_odds
    name: "Entertainment Zone 1 — The Long Odds"
    exits:
      north: ez1_promenade_c
      south: ez1_ink_and_iron
  - id: ez1_ink_and_iron
    name: "Entertainment Zone 1 — Ink & Iron"
    exits:
      north: ez1_long_odds
  - id: ez1_promenade_e
    name: "Entertainment Zone 1 — Promenade (East)"
    exits:
      west: ez1_promenade_c
      north: ez1_midnight_revue
      south: ez1_velvet_hour
      east: ez1_last_laugh
  - id: ez1_midnight_revue
    name: "Entertainment Zone 1 — The Midnight Revue"
    exits:
      south: ez1_promenade_e
  - id: ez1_velvet_hour
    name: "Entertainment Zone 1 — The Velvet Hour"
    exits:
      north: ez1_promenade_e
      east: ez1_humidor
  - id: ez1_humidor
    name: "Entertainment Zone 1 — The Humidor"
    exits:
      west: ez1_velvet_hour
  - id: ez1_last_laugh
    name: "Entertainment Zone 1 — The Last Laugh"
    exits:
      west: ez1_promenade_e
`;
const PROMENADE = "The Promenade — Entertainment Zone 1's neon-soaked main drag, signs buzzing " +
    "and flickering overhead and music bleeding from every doorway. It runs on.";
function ez1Default(_r) {
    return PROMENADE;
}
function stopDescription(s) {
    return ("The TravelTube stop for Entertainment Zone 1 — and the moment the doors " +
        "open the place announces itself: a wash of coloured light, a low thud of " +
        "bass from somewhere out of sight, and the mingled smell of perfume, spilled " +
        "drink and frying food. This is the after-dark end of Horizon, and it does " +
        "not keep daytime hours. " +
        (s.flags["pod_summoned_at"] === "ez1_tube_stop"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        "\n\nThe Promenade runs east; a cloakroom and the toilets are tucked away " +
        "to the south.");
}
const built = buildAreaFromYaml(ENTERTAINMENT_ZONE_1_YAML, {
    defaultDescription: ez1Default,
    rooms: {
        ez1_tube_stop: {
            description: stopDescription,
            items: ["reader_ez1"],
        },
        ez1_cloakroom: {
            description: "A long counter for coats and bags, watched over by a bored attendant, " +
                "with the toilets beyond — a handy place to begin or salvage a night. " +
                "The Promenade is back north.",
        },
        ez1_promenade_w: {
            description: "The west end of the Promenade, where the night gets going. The Brass " +
                "Rail — a proper drinking bar — stands to the north; the all-hours glow " +
                "of the Stardust Diner spills from the south. The Promenade continues " +
                "east, deeper into the noise; the 'Tube stop is back west.",
        },
        ez1_brass_rail: {
            onEnter: syncBarNpcs,
            scenery: {
                bar: "A long bar of dark wood, worn smooth, with a brass foot-rail running its length. BUY a DRINK and join the companionable hum.",
                bottles: "Ranks of bottles behind the bar, lit from below like a small city skyline. Most of them you couldn't name; all of them you could probably afford one of.",
                mirror: "A long mirror behind the bottles, fogged at the corners, doubling the skyline of glass and quietly letting you watch the room without turning round.",
                "foot-rail": "A brass foot-rail, polished bright by a century of boots and the particular stance of people settling in for the duration.",
                rail: "A brass foot-rail, polished bright by a century of boots and the particular stance of people settling in for the duration.",
                bartender: "The bartender has the unhurried competence of someone who has poured for every kind of trouble and judged none of it. They are not, you note, in any hurry to be asked questions.",
                stools: "Bar stools worn smooth, each one shaped by the same regulars holding the same opinions night after night.",
                door: "A narrow door at the back, easy to miss, leading east into a smaller, quieter room.",
            },
            description: "The Brass Rail — a proper bar: dark wood, a long brass foot-rail, and a " +
                "mirror behind ranks of bottles lit like a small skyline. The light is " +
                "low, the stools are worn smooth, and the bartender has the unhurried " +
                "competence of someone who has poured for every kind of trouble and " +
                "judged none of it. Taps, spirits, and the companionable hum of people " +
                "drinking with intent. A narrow door at the back leads east into a " +
                "smaller, quieter room. The Promenade is back south.",
        },
        ez1_long_shot: {
            onEnter: syncBarNpcs,
            scenery: {
                table: "A handful of small, ring-marked tables. You could SIT at one, BUY a DRINK, and let the evening — and the company — come to you.",
                tables: "A handful of small, ring-marked tables. You could SIT at one, BUY a DRINK, and let the evening — and the company — come to you.",
                bar: "A short bar along one wall, a few bottles, an unhurried barman. Drinks are cheap and the measures honest, which is most of what the regulars ask of the place.",
                stool: "Worn bar stools, polished smooth by years of the same half-dozen backsides.",
            },
            description: "The Long Shot — a back bar behind the Brass Rail, reached through a " +
                "narrow door that most of the evening crowd never notices. Smaller, " +
                "quieter, with the same worn-wood bones but none of the sociable energy " +
                "out front: a handful of tables, a short bar, and the feeling of a place " +
                "where the same half-dozen faces come every night and would prefer it " +
                "stayed that way. Dim, unhurried, and honest about what it is. The Brass " +
                "Rail is back west.",
        },
        ez1_stardust_diner: {
            scenery: {
                booths: "Cracked-vinyl booths along the windows, each one holding somebody's small hours — the hungry, the drunk, the heartbroken. BUY a BREAKFAST and join them.",
                booth: "A cracked-vinyl booth by the window, the table wiped but not quite clean, the seat sighing as you imagine sitting in it.",
                counter: "A long counter fronting the griddle, chrome and crumbs, a row of stools and a coffee machine that never quite stops. BUY a BREAKFAST, a COFFEE, or a DRINK.",
                griddle: "A griddle that never quite cools, glistening with the ghosts of a thousand fry-ups. The cook works it without appearing to look.",
                sign: "A flickering sign that's lost its 'r' — the STA DUST DINER, open all hours, and somehow the better for the fault.",
                coffee: "The coffee here is terrible and bottomless, and at four in the morning it is the best coffee in the world. BUY a COFFEE and see.",
            },
            description: "The Stardust Diner — chrome, cracked vinyl, and a sign that flickers on " +
                "the 'r'. Open all hours for the hungry, the drunk, and the heartbroken; " +
                "booths along the windows, a counter fronting a griddle that never quite " +
                "cools. The coffee is terrible and bottomless, and at four in the morning " +
                "it is the best place in the world. The Promenade is back north.",
        },
        ez1_promenade_c: {
            description: "The middle of the Promenade, and the loudest stretch of it. Bass pours " +
                "out of Eclipse to the north, its doorway a throb of light and sound; to " +
                "the south the Long Odds gaming house glitters, all soft chimes and " +
                "softer promises. The Promenade runs east and west.",
        },
        ez1_eclipse: {
            scenery: {
                "dance floor": "A heaving, strobe-lit press of bodies, the bass felt in the breastbone as much as heard. Joining it is a decision you can make sober for about another thirty seconds.",
                floor: "A heaving, strobe-lit press of bodies, the bass felt in the breastbone as much as heard.",
                bar: "A long bar down one side, three deep with people shouting orders they can't hear themselves place. BUY a DRINK, if you can get served.",
                dj: "A DJ presides from a lit booth above the crowd, hands moving, head down, entirely in charge of three hundred people's heartrates.",
                lasers: "Sweeping lasers cut the dark into moving slabs of colour, picking out faces for an instant and losing them again.",
                rope: "A velvet rope and a watchful host guard the stair up to the VIP lounge — north, if your face or your credits fit.",
            },
            description: "Eclipse — the zone's big nightclub, and it is LOUD: a cavern of dark " +
                "split by sweeping lasers and the strobe-lit press of bodies on the " +
                "dance floor, the bass felt in the breastbone as much as heard. A DJ " +
                "presides from a lit booth above the crowd; a long bar runs down one " +
                "side, three deep with people shouting orders they can't hear " +
                "themselves place. A velvet rope and a watchful host guard a stair up to " +
                "the VIP lounge, north. The way out is back south.",
        },
        ez1_eclipse_vip: {
            scenery: {
                booths: "Velvet booths above the worst of the noise, each holding a clientele paying handsomely for quiet, privacy, and the being-seen-to-afford-it.",
                booth: "A velvet booth, deep and discreet, the kind of seat that costs more empty than most tables cost full.",
                bar: "A private bar, unhurried and overstaffed, where the measures are generous and the prices are not. BUY a COCKTAIL.",
                glass: "Through the glass, the dance floor seethes below like weather you're glad to be out of.",
            },
            description: "Eclipse's VIP lounge — above the worst of the noise, a hush of velvet " +
                "booths, a private bar, and a clientele paying handsomely for the quiet " +
                "and the privacy and the being-seen-to-afford-it. Through the glass the " +
                "dance floor seethes below like weather you're glad to be out of. The " +
                "club is back down, south.",
        },
        ez1_long_odds: {
            scenery: {
                machine: "A bank of slot machines, each a tower of velvet trim and restless light, " +
                    "humming a chord pitched (you'd swear) to loosen the wallet. The label glows the " +
                    "same on every one: LOAD 50 TO PLAY. You can PLAY (or SPIN) one — fifty credits a go.",
                machines: "A bank of slot machines, each a tower of velvet trim and restless light, " +
                    "humming a chord pitched (you'd swear) to loosen the wallet. The label glows the " +
                    "same on every one: LOAD 50 TO PLAY. You can PLAY (or SPIN) one — fifty credits a go.",
                slot: "A slot machine: three reels, a scatter of bright symbols, and a payout table no " +
                    "one ever reads twice. LOAD 50 TO PLAY. PLAY or SPIN to try your luck.",
                slots: "A slot machine: three reels, a scatter of bright symbols, and a payout table no " +
                    "one ever reads twice. LOAD 50 TO PLAY. PLAY or SPIN to try your luck.",
                reels: "Cherries, bells, plums, stars, bars — and, very occasionally, a row of lucky " +
                    "sevens that everyone in the room is here, fundamentally, to chase.",
                table: "Card tables and a roulette wheel work the centre, dealers in deep red moving " +
                    "with practised, unhurried calm. The smart money is watching the machines; you could " +
                    "PLAY one of those.",
                wheel: "A roulette wheel turns under a low gold lamp, the ball skittering and settling, " +
                    "skittering and settling. The croupier never stops smiling.",
            },
            description: "The Long Odds — a gaming house done out in deep red and gold, the air " +
                "conditioned and faintly scented, the whole place engineered so you " +
                "forget what hour it is. Card tables and a roulette wheel work the " +
                "centre; ranks of slot machines chirp and flash along the walls, every " +
                "one glowing the same invitation: LOAD 50 TO PLAY. Everyone smiles at " +
                "you here. The house, naturally, always wins — you could PLAY (or SPIN) " +
                "a machine and find out how. The Promenade is back north; a tattoo " +
                "studio, Ink & Iron, opens off to the south.",
        },
        ez1_ink_and_iron: {
            scenery: {
                flash: "Walls papered with flash designs and photos of finished work — anchors and roses and several things you'd want to be much drunker to choose.",
                designs: "Flash designs sheeted on the walls, a menu of permanent decisions priced by size and regret.",
                artists: "A couple of artists bend under angled lamps, the buzz of a needle rising and falling, entirely indifferent to your hesitation.",
                needle: "A tattoo needle, buzzing under an angled lamp, making someone else's long night into a permanent one.",
                photos: "Photos of finished work, glossy and proud, the before-and-afters of a hundred long nights that turned into permanent decisions.",
            },
            description: "Ink & Iron — a tattoo and piercing studio, clean and bright against the " +
                "casino's plush gloom, its walls papered with flash designs and photos " +
                "of finished work. A couple of artists bend under angled lamps, the buzz " +
                "of a needle rising and falling. The kind of place where a long night " +
                "turns into a permanent decision. The Long Odds is back north.",
        },
        ez1_promenade_e: {
            description: "The east end of the Promenade, where the entertainment turns to " +
                "performance. The Midnight Revue's marquee blazes to the north; the " +
                "Velvet Hour, a cocktail lounge, glows discreetly to the south; and at " +
                "the very end, east, sits the Last Laugh comedy club. West, the " +
                "Promenade runs back toward the bass and the lights.",
        },
        ez1_midnight_revue: {
            scenery: {
                stage: "A curtained stage at the front, a torch singer somewhere in the middle of a number, the spotlight doing most of the costuming.",
                singer: "A torch singer, mid-number, holding the room on a long note and a longer glance. Burlesque, song, and the occasional act that defies easy description.",
                tables: "Small round tables clustered before the stage, each with its own shaded lamp and its own quiet little drama. BUY a DRINK and settle in.",
                table: "A small round table with a shaded lamp, close enough to the stage to be implicated in the act.",
                curtain: "A heavy stage curtain, tarnished gilt at the edges, hiding whatever the next number needs hiding until it doesn't.",
            },
            description: "The Midnight Revue — a cabaret theatre of red plush and tarnished gilt, " +
                "small round tables clustered before a curtained stage, each with its " +
                "own shaded lamp. A torch singer is somewhere in the middle of a number, " +
                "and the room smells of perfume and anticipation. Burlesque, song, and " +
                "the occasional act that defies easy description — all strictly after " +
                "dark. The Promenade is back south.",
        },
        ez1_velvet_hour: {
            scenery: {
                pianist: "A pianist plays standards nobody quite listens to, which is rather the point — music as upholstery, soft and expensive.",
                piano: "A baby grand in the corner, lid down, a glass of something untouched on the edge of it.",
                seats: "Deep, low seats that invite you to stay and order another. The whole room is a gracious apology for the racket outside.",
                drinks: "The drinks arrive as small, expensive works of art. BUY a COCKTAIL and admire one before you ruin it.",
            },
            description: "The Velvet Hour — a low-lit cocktail lounge, all hush and polish, where " +
                "a pianist plays standards nobody quite listens to and the drinks arrive " +
                "as small, expensive works of art. The seats are deep, the conversations " +
                "low, the whole room a gracious apology for the racket outside. The " +
                "Promenade is back north; a door leads east into the Humidor.",
        },
        ez1_humidor: {
            scenery: {
                whiskies: "A wall of aged whiskies under brass lamps, the labels a roll-call of distilleries and decades. BUY a WHISKY and pick a quiet corner.",
                whisky: "Aged whiskies racked under brass lamps — peat and sherry and a great deal of money. BUY a WHISKY.",
                cigars: "Cigars kept at their proper humidity behind glass, ranked by length and provenance. BUY a CIGAR and smoke it in one of the deep chairs.",
                cigar: "A cigar, kept at exactly the right humidity, waiting to cost you twelve credits and an hour of doing nothing. BUY a CIGAR.",
                armchairs: "Leather armchairs, deep and unbothered, arranged for slow conversation and slower smoke.",
                chairs: "Leather armchairs, deep and unbothered, arranged for slow conversation and slower smoke.",
                smoke: "The slow blue drift of good cigar smoke hangs beneath a soft hush of extraction, somehow more atmosphere than nuisance.",
            },
            description: "The Humidor — a snug, panelled den behind the lounge: leather " +
                "armchairs, a wall of aged whiskies under brass lamps, and the slow blue " +
                "drift of good cigar smoke beneath a soft hush of extraction. " +
                "Spotlessly kept, quietly exclusive, and entirely unbothered by the " +
                "hour. The Velvet Hour is back west.",
        },
        ez1_last_laugh: {
            scenery: {
                stage: "A low stage under one hard spotlight, where someone is dying in front of a tough crowd — and the crowd is loving every second of it.",
                microphone: "A microphone on a lonely stand, the loneliest object in the room, currently being failed by its operator.",
                mic: "A microphone on a lonely stand, the loneliest object in the room, currently being failed by its operator.",
                chairs: "Rows of mismatched chairs packed too close together, the audience's knees and elbows part of the act whether they like it or not.",
                comic: "Up there under the spotlight, a comic learning the hard way that this crowd came to watch a fight, not a set.",
            },
            description: "The Last Laugh — a brick-walled comedy club: a low stage under one hard " +
                "spotlight, a microphone on a lonely stand, and rows of mismatched " +
                "chairs packed too close together. Someone is dying up there in front of " +
                "a tough crowd, and the crowd is loving every second of it. Two-drink " +
                "minimum; no mercy. The Promenade is back west.",
        },
    },
});
export const entertainment1Rooms = built.rooms;
