// Entertainment Zone 2 — the Arcade (CANON). Horizon Outpost's bright, loud,
// joyous games arcade. Built from maps/entertainment_zone_2.yaml via
// buildAreaFromYaml.
//
// One open, easy-to-navigate space: the entrance machine floor (ez2_tube_stop,
// also the TravelTube stop) opens south into a social hub of tables, with the
// pool tables (east), a refreshment counter (south), and a beanbag lounge (west)
// off it. 'Tube-only — declared in its index.ts MODULES entry (reader_ez2). No
// walking link to the rest of the outpost.
//
// Tone (canon): a riot of light and sound, warm electronics and spilled soft
// drinks — but, past the noise, just people being happy. Prose is full starter
// content; playable games / NPCs come in a later pass.
import { buildAreaFromYaml } from "./area.js";
const ENTERTAINMENT_ZONE_2_YAML = `
# Generated by tools/mapper.html
area: entertainment_zone_2
areaName: "Entertainment Zone 2"
stop: ez2_tube_stop
rooms:
  - id: ez2_tube_stop
    name: "Entertainment Zone 2 — Arcade Floor"
    stop: true
    exits:
      south: ez2_social_area
  - id: ez2_social_area
    name: "Entertainment Zone 2 — Social Area"
    exits:
      north: ez2_tube_stop
      east: ez2_pool_tables
      south: ez2_refreshment
      west: ez2_chill_area
  - id: ez2_pool_tables
    name: "Entertainment Zone 2 — Pool Tables"
    exits:
      west: ez2_social_area
  - id: ez2_refreshment
    name: "Entertainment Zone 2 — Refreshment Counter"
    exits:
      north: ez2_social_area
  - id: ez2_chill_area
    name: "Entertainment Zone 2 — Beanbag Lounge"
    exits:
      east: ez2_social_area
`;
function ez2Default(_r) {
    return "A bright, noisy corner of the arcade.";
}
function stopDescription(s) {
    return ("The travel-tube doors open and the noise hits you like a wall. The arcade " +
        "stretches out before you in a riot of light and sound — banks of gaming " +
        "machines line the walls, each one clamouring for attention with flashing " +
        "sequences of colour, electronic fanfares, and the clatter of play. The air " +
        "smells faintly of warm electronics and spilled soft drinks; voices and " +
        "laughter ricochet off every surface into a constant, exhilarating din that " +
        "makes it almost impossible to think straight. " +
        (s.flags["pod_summoned_at"] === "ez2_tube_stop"
            ? "Back at the doors, a pod waits in the bay — you can BOARD it."
            : "Back at the travel-tube doors, scan your ID at the reader to summon a pod.") +
        "\n\nPast the entrance, the floor opens up to the south into a wider social " +
        "area.");
}
const built = buildAreaFromYaml(ENTERTAINMENT_ZONE_2_YAML, {
    defaultDescription: ez2Default,
    rooms: {
        ez2_tube_stop: {
            description: stopDescription,
            items: ["reader_ez2"],
            scenery: {
                machines: "Banks of gaming machines line the walls, each clamouring for attention with flashing colour, electronic fanfares and the clatter of play. Cabinets of every vintage, all of them loud.",
                machine: "A gaming machine, mid-attract-loop, promising fun and small fortunes in equal, flashing measure.",
                games: "Games of every kind — driving, shooting, dancing, things with no obvious rules at all — wall to wall and floor to ceiling.",
            },
        },
        ez2_social_area: {
            scenery: {
                tables: "A row of well-worn tables, perpetually occupied — the kind of spot where people congregate between games or simply sit and watch the chaos unfold.",
                table: "A well-worn table, ring-marked and a little sticky, claimed by spectators and resters alike.",
                people: "Players, between games and after them: laughing, arguing, slumped, triumphant. Past the noise and the light, just people being happy.",
            },
            description: "The arcade's social area, where the floor opens out and you can hear " +
                "yourself think — almost. A row of well-worn tables sits to one side, " +
                "perpetually occupied: the kind of spot where people congregate between " +
                "games or simply sit and watch the chaos unfold. Look past the noise and " +
                "the light, and it's just people being happy — which, once you're used " +
                "to it, isn't such a bad thing at all.\n\nThe machine floor is back " +
                "north; pool tables are off to the east, a refreshment counter to the " +
                "south, and a cluster of beanbags and low seating to the west.",
        },
        ez2_pool_tables: {
            npcs: ["brinn"],
            scenery: {
                "pool table": "Green felt lit from above, a game in progress and, as often as not, money on it. The good players don't look up; the bad ones won't shut up.",
                "pool tables": "A cluster of pool tables under low lamps, balls clacking, cues chalked, the usual small wagers riding on the usual small games.",
                table: "Green felt lit from above, a game in progress and, as often as not, money on it.",
                tables: "A cluster of pool tables under low lamps, balls clacking, cues chalked, the usual small wagers riding on the usual small games.",
                cues: "Racks of cues fixed to the wall, used and abused in roughly equal measure — a couple have seen action that was never about pool.",
                cue: "A pool cue off the wall rack, the tip worn, the shaft straighter than you'd expect for the company it keeps.",
                felt: "Green felt, lit hard from above, marked with the ghosts of a thousand games.",
            },
            description: "A cluster of pool tables dominating a substantial stretch of floor — " +
                "green felt lit from above, racks of used and abused cues fixed to the " +
                "walls nearby. There's usually a game on, and as often as not money on " +
                "it. The social area is back west.",
        },
        ez2_refreshment: {
            scenery: {
                counter: "A small, sticky counter doing brisk trade in fizzy drinks, hot snacks, and caffeine in roughly the quantities an arcade demands. BUY a DRINK or a SNACK here.",
                drinks: "Fizzy drinks in violent colours, lined up cold and waiting. BUY a DRINK if you're parched from all the not-playing.",
                snacks: "Hot snacks under a lamp — salty, greasy, moreish, and entirely beside the point of the place. BUY a SNACK.",
            },
            description: "A small refreshment counter serving drinks and snacks to a steady " +
                "stream of thirsty players — fizzy drinks, hot snacks, and sugar and " +
                "caffeine in roughly the quantities an arcade demands. The social area " +
                "is back north.",
        },
        ez2_chill_area: {
            scenery: {
                beanbags: "A scatter of beanbags and low, shapeless seating, half-claimed by players slumped in the afterglow of a famous victory or a narrow defeat.",
                beanbag: "A beanbag that has moulded itself to a hundred different exhausted shapes. You could SIT, frankly.",
                seating: "Low, shapeless seating with no opinions about posture — somewhere to collapse when the games get too much.",
            },
            description: "A scatter of beanbags and low, shapeless seating — somewhere to " +
                "collapse when the games get too much, half-claimed by players slumped " +
                "in the afterglow of a famous victory or a narrow defeat. It's even, " +
                "relatively speaking, a little quieter here. The social area is back " +
                "east.",
        },
    },
});
export const entertainment2Rooms = built.rooms;
