// The Industrial Sector — the station's working quarter: a warren of narrow
// corridors threading between workshops, with Burke's workshop and a painting
// chamber tucked at the far ends. Reachable two ways: by TravelTube (its own
// stop, horizon_tube_stop, declared in its index.ts MODULES entry with the
// reader_industrial item) and ON FOOT from the Bazaar (the Industrial Sector
// accessway → horizon_narrow_corridor). Built from maps/industrial_sector.yaml
// via buildAreaFromYaml.
//
// Descriptions are placeholder/starter prose — enough to navigate and read
// coherently while the sector's content (Burke, the workshops' wares, the
// painting chamber) is filled in later.
import { buildAreaFromYaml } from "./area.js";
const INDUSTRIAL_SECTOR_YAML = `
# Generated by tools/mapper.html
area: industrial_sector
areaName: "Industrial Sector"
stop: horizon_tube_stop
rooms:
  - id: horizon_narrow_corridor
    name: "Narrow corridor"
    exits:
      north: horizon_narrow_corridor2
  - id: horizon_narrow_corridor2
    name: "Narrow corridor"
    exits:
      north: horizon_t_junction
      south: horizon_narrow_corridor
  - id: horizon_t_junction
    name: "T junction"
    exits:
      north: horizon_tube_stop
      south: horizon_narrow_corridor2
      east: horizon_narrow_corridor3
  - id: horizon_tube_stop
    name: "'Tube stop"
    stop: true
    exits:
      south: horizon_t_junction
  - id: horizon_narrow_corridor3
    name: "Narrow corridor"
    exits:
      east: horizon_narrow_corridor4
      west: horizon_t_junction
  - id: horizon_narrow_corridor4
    name: "Narrow corridor"
    exits:
      north: horizon_small_workshop
      south: horizon_storage_cupboard
      east: horizon_narrow_corridor5
      west: horizon_narrow_corridor3
  - id: horizon_narrow_corridor5
    name: "Narrow corridor"
    exits:
      east: horizon_narrow_corridor6
      west: horizon_narrow_corridor4
  - id: horizon_narrow_corridor6
    name: "Narrow corridor"
    exits:
      north: horizon_narrow_corridor7
      south: horizon_narrow_corridor9
      west: horizon_narrow_corridor5
  - id: horizon_narrow_corridor7
    name: "Narrow corridor"
    exits:
      north: horizon_narrow_corridor8
      south: horizon_narrow_corridor6
      east: horizon_welding_workshop
      west: horizon_medium_workshop
  - id: horizon_small_workshop
    name: "Small workshop"
    exits:
      south: horizon_narrow_corridor4
  - id: horizon_storage_cupboard
    name: "Storage cupboard"
    exits:
      north: horizon_narrow_corridor4
  - id: horizon_medium_workshop
    name: "Medium workshop"
    exits:
      east: horizon_narrow_corridor7
  - id: horizon_welding_workshop
    name: "Welding workshop"
    exits:
      west: horizon_narrow_corridor7
  - id: horizon_narrow_corridor8
    name: "Narrow corridor"
    exits:
      south: horizon_narrow_corridor7
      east: horizon_burke_s_workshop
  - id: horizon_burke_s_workshop
    name: "Burke's workshop"
    exits:
      west: horizon_narrow_corridor8
  - id: horizon_narrow_corridor9
    name: "Narrow corridor"
    exits:
      north: horizon_narrow_corridor6
      south: horizon_narrow_corridor10
  - id: horizon_narrow_corridor10
    name: "Narrow corridor"
    exits:
      north: horizon_narrow_corridor9
      east: horizon_narrow_corridor11
  - id: horizon_narrow_corridor11
    name: "Narrow corridor"
    exits:
      north: horizon_painting_chamber
      west: horizon_narrow_corridor10
  - id: horizon_painting_chamber
    name: "Painting chamber"
    exits:
      south: horizon_narrow_corridor11
`;
const NARROW_CORRIDOR = "A narrow service corridor, bare structural metal underfoot and overhead, " +
    "the hum of the station's working systems carrying through the walls. " +
    "Identical stretches of it run off in several directions — it would be easy " +
    "to lose your bearings in here.";
const WORKSHOP = "A workshop off the Industrial Sector corridors — benches, racked tools, and " +
    "part-finished work left where it was set down. The corridor is back the way " +
    "you came.";
// Per-room starter prose for the feature rooms. Plain placeholders for now — the
// real contents (wares, machinery, Burke himself) come later.
const FEATURES = {
    horizon_small_workshop: "A small workshop, barely more than a bench and a wall of hand tools, the " +
        "floor swept and the work close and fiddly. The corridor is back south.",
    horizon_medium_workshop: "A medium-sized workshop, machine tools bolted to the deck and a haze of " +
        "metal dust in the air. The corridor is back east.",
    horizon_welding_workshop: "A welding workshop — scorched benches, gas bottles chained to the wall, " +
        "and the sharp afterglow smell of recent work. The corridor is back west.",
    horizon_burke_s_workshop: "Burke's workshop — the heavy door slides shut behind you with its " +
        "characteristic noisy, clunky rattle. Inside, a sprawling mess of cluttered " +
        "benches " +
        "scattered with tools, half-built devices, and bundles of wires that hang " +
        "like vines from the ceiling; loose parts and components are strewn across " +
        "every available surface. A faint haze of smoke lingers in the air, " +
        "carrying the pungent scent of burning metal and plastic, and the dull " +
        "lighting casts everything in a flat, workmanlike glow.\n\n" +
        "Despite the apparent chaos, there is an underlying sense of order here — " +
        "this is a place where questionable things happen with professional " +
        "precision. A terminal sits on one of the benches. A heavy workbench " +
        "occupies the centre of the space, its surface bearing the scars of a " +
        "thousand jobs. Shelves along the walls hold components, refurbished " +
        "parts, and items whose purpose is not immediately obvious. There is no " +
        "one here who asks unnecessary questions.\n\n" +
        "The corridor is back west.",
    horizon_storage_cupboard: "A cramped storage cupboard, shelving crammed with spares, consumables and " +
        "the unlabelled boxes every working space accumulates. The corridor is back " +
        "north.",
    horizon_painting_chamber: "A painting chamber — a sealed bay with extraction hoods overhead and the " +
        "faint chemical tang of solvent and fresh finish. The corridor is back " +
        "south; off the far side, a long, plain pedestrian walkway leads away " +
        "north toward the Lower Commercial District.",
};
function stopDescription(s) {
    return ("The Industrial Sector's TravelTube stop — a functional little bay set into " +
        "the bare metal of the working quarter, a reader mounted on the wall. " +
        (s.flags["pod_summoned_at"] === "horizon_tube_stop"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        " A corridor leads south into the sector proper.");
}
function industrialDefault(r) {
    if (FEATURES[r.id])
        return FEATURES[r.id];
    const n = r.name.toLowerCase();
    if (n.includes("junction"))
        return ("A T-junction in the Industrial Sector corridors. The 'Tube stop lies " +
            "north; the corridors branch away south and east into the warren of " +
            "workshops.");
    if (n.includes("workshop"))
        return WORKSHOP;
    return NARROW_CORRIDOR;
}
const built = buildAreaFromYaml(INDUSTRIAL_SECTOR_YAML, {
    defaultDescription: industrialDefault,
    rooms: {
        horizon_tube_stop: {
            description: stopDescription,
            items: ["reader_industrial"],
        },
        // Burke works nights only (see burke.ts); his door is gated by day below.
        horizon_burke_s_workshop: {
            npcs: ["burke"],
            items: ["burke_reader"],
        },
    },
});
// Night-only access: Burke's workshop door (corridor 8 → east) is shut by day.
built.rooms["horizon_narrow_corridor8"].exits.east = {
    to: "horizon_burke_s_workshop",
    gated: (s) => (s.isDaytime
        ? "The workshop's heavy door is shut fast, a hand-lettered card wedged in the frame: BACK AT NIGHT. " +
            "Burke, it seems, doesn't do daylight."
        : null),
};
// Cross-area, on-foot link back south into the Bazaar (the Bazaar side of this
// link is wired in bazaar.ts). The mapper drops cross-area exits.
built.rooms["horizon_narrow_corridor"].exits.south =
    { to: "horizon_industrial_sector_accessway", description: "the Bazaar" };
// Cross-area, on-foot link: a long, nondescript walkway north out of the far
// (painting-chamber) corner to the Lower Commercial District (Sector 4). The
// district side's reciprocal south is wired in lower_commercial.ts.
built.rooms["horizon_painting_chamber"].exits.north =
    { to: "lcd_walkway_3", description: "the Lower Commercial District" };
export const industrialRooms = built.rooms;
