// Lower Commercial District (Sector 4) — a dim, narrow, labyrinthine district
// set well apart from Horizon's bright main concourse, where the more discreet
// businesses cluster. Built from maps/lower_commercial_district.yaml via
// buildAreaFromYaml.
//
// Two canon key locations:
//   - Dr Rajah's Pharmaceutical Supplies (lcd_rajah_front): a clean, well-kept
//     medical-retail shopfront; a beaded curtain leads back (north) to a small
//     consultation room (lcd_rajah_back). Dr Rajah is "a medical practitioner
//     with a sideline in retail".
//   - Teng Vessel Brokerage (lcd_teng_brokerage): a second-hand ship dealer,
//     a small tidy office wedged between a scrap dealer (west) and a nutrition-
//     supplement vendor (east). On the defect pathway he points the PC at the
//     shipyard hauler to stow away on (the berth pointer; see lcd_npcs.ts).
//
// Access (two ways): its own TravelTube stop (lcd_tube_stop, declared in its
// index.ts MODULES entry, reader_lcd) AND a long, nondescript
// pedestrian walkway south to the Industrial Sector's painting chamber (the
// far-from-the-'Tube-stop corner). Descriptions are placeholder/starter prose
// — canon-informed for the two key locations, generic-by-kind elsewhere.
import { buildAreaFromYaml } from "./area.js";
import { FLAG_RAJAH_HOME_MET } from "./flags.js";
const LOWER_COMMERCIAL_YAML = `
# Generated by tools/mapper.html
area: lower_commercial_district
areaName: "Lower Commercial District (Sector 4)"
stop: lcd_tube_stop
rooms:
  - id: lcd_tube_stop
    name: "Lower Commercial District — TravelTube Stop"
    stop: true
    exits:
      south: lcd_concourse
  - id: lcd_concourse
    name: "Lower Commercial District — Concourse"
    exits:
      north: lcd_tube_stop
      south: lcd_corridor_1
      east: lcd_corridor_e1
      west: lcd_corridor_w1
  - id: lcd_corridor_w1
    name: "Lower Commercial District — Dim Corridor"
    exits:
      east: lcd_concourse
      west: lcd_corridor_w2
  - id: lcd_corridor_w2
    name: "Lower Commercial District — Narrow Passage"
    exits:
      east: lcd_corridor_w1
      west: lcd_blind_alley
      north: lcd_rajah_front
  - id: lcd_blind_alley
    name: "Lower Commercial District — Blind Alley"
    exits:
      east: lcd_corridor_w2
  - id: lcd_rajah_front
    name: "Lower Commercial District — Rajah's Pharmaceutical Supplies"
    exits:
      south: lcd_corridor_w2
      north: lcd_rajah_back
  - id: lcd_rajah_back
    name: "Lower Commercial District — Rajah's Consultation Room"
    exits:
      south: lcd_rajah_front
  - id: lcd_corridor_e1
    name: "Lower Commercial District — Narrow Passage"
    exits:
      west: lcd_concourse
      east: lcd_corridor_e2
  - id: lcd_corridor_e2
    name: "Lower Commercial District — Dim Corridor"
    exits:
      west: lcd_corridor_e1
      east: lcd_brokers_alley
      north: lcd_scrap_dealer
  - id: lcd_scrap_dealer
    name: "Lower Commercial District — Scrap Dealer"
    exits:
      south: lcd_corridor_e2
  - id: lcd_brokers_alley
    name: "Lower Commercial District — Narrow Passage"
    exits:
      west: lcd_corridor_e2
      east: lcd_corridor_e3
      north: lcd_teng_brokerage
  - id: lcd_teng_brokerage
    name: "Lower Commercial District — Teng Vessel Brokerage"
    exits:
      south: lcd_brokers_alley
  - id: lcd_corridor_e3
    name: "Lower Commercial District — Cramped Junction"
    exits:
      west: lcd_brokers_alley
      north: lcd_supplement_vendor
      east: lcd_back_passage
  - id: lcd_supplement_vendor
    name: "Lower Commercial District — Nutrition Supplement Vendor"
    exits:
      south: lcd_corridor_e3
  - id: lcd_back_passage
    name: "Lower Commercial District — Service Alley"
    exits:
      west: lcd_corridor_e3
      south: lcd_back_passage_2
  - id: lcd_back_passage_2
    name: "Lower Commercial District — Service Alley"
    exits:
      north: lcd_back_passage
      west: lcd_corridor_2
  - id: lcd_corridor_1
    name: "Lower Commercial District — Low Archway"
    exits:
      north: lcd_concourse
      south: lcd_corridor_2
      east: lcd_pawnshop
      west: lcd_noodle_counter
  - id: lcd_pawnshop
    name: "Lower Commercial District — Pawnbroker"
    exits:
      west: lcd_corridor_1
  - id: lcd_noodle_counter
    name: "Lower Commercial District — Noodle Counter"
    exits:
      east: lcd_corridor_1
  - id: lcd_corridor_2
    name: "Lower Commercial District — Dim Corridor"
    exits:
      north: lcd_corridor_1
      south: lcd_walkway_1
      east: lcd_back_passage_2
  - id: lcd_walkway_1
    name: "Lower Commercial District — Long Walkway"
    exits:
      north: lcd_corridor_2
      south: lcd_walkway_2
  - id: lcd_walkway_2
    name: "Lower Commercial District — Long Walkway"
    exits:
      north: lcd_walkway_1
      south: lcd_walkway_3
  - id: lcd_walkway_3
    name: "Lower Commercial District — Long Walkway"
    exits:
      north: lcd_walkway_2
      south: horizon_painting_chamber
`;
// --- Generic, by-kind corridor prose (the labyrinth's connective tissue). ----
// Repeated room names + repeated descriptions are the maze effect; the
// auto-signposted exits ("east (Concourse)") keep it navigable.
const DIM_CORRIDOR = "A dim corridor, the lighting tired and yellowish where the bright main " +
    "concourse far above has clean white light to spare. The walls press close " +
    "and the businesses behind them keep their custom to themselves. It runs on.";
const NARROW_PASSAGE = "A narrow passage, barely wide enough for two to pass, the air close and the " +
    "signage hand-lettered or absent. Easy to lose your bearings down here.";
const JUNCTION = "A cramped junction where several passages meet at awkward angles. Nothing " +
    "marks which is which; the district seems designed to be confusing.";
// The concourse directory board — the district's one concession to wayfinding,
// so a vague rumour (Burke's "west off the concourse") can actually be followed.
const LCD_DIRECTORY = "A scuffed directory board, half its entries scratched out or faded, but " +
    "enough survives to steer by:\n" +
    "  WEST  - Rajah's Pharmaceutical Supplies (then north)\n" +
    "  EAST  - Scrap Dealer, then on to Teng Vessel Brokerage & the supplement vendor\n" +
    "  SOUTH - Noodle Counter, Pawnbroker, and the long walkway out of the district";
function lowerCommercialDefault(r) {
    const n = r.name.toLowerCase();
    if (n.includes("blind alley"))
        return "A blind alley — a few stacked crates, a dead utility panel, and no way on. Back east is the only way out.";
    if (n.includes("service alley"))
        return "A grimy service alley running behind the shopfronts, ducting overhead and the back doors of businesses that would rather you used the front. It threads on.";
    if (n.includes("low archway"))
        return "A low archway where the ceiling drops and you instinctively duck. Passages open off in several directions.";
    if (n.includes("long walkway"))
        return ("A long, plain pedestrian walkway — bare decking, evenly spaced lights, " +
            "and not one thing to look at. It passes beneath the underside of " +
            "something vast and quiet overhead; residences, most likely, going about " +
            "their lives with no idea anyone walks below. It runs on, dully, north " +
            "and south.");
    if (n.includes("scrap dealer"))
        return "A scrap dealer's: bins and shelves of salvaged parts, cabling by the metre, and components priced by weight rather than function. The passage is back south.";
    if (n.includes("supplement vendor"))
        return "A nutrition-supplement vendor — tubs and sachets of powders and pressed bars wall to wall, the labelling long on promises and short on specifics. The passage is back south.";
    if (n.includes("pawnbroker"))
        return "A pawnbroker's, its window a jumble of other people's hard times: tools, instruments, a few items best not asked about. The corridor is back west.";
    if (n.includes("noodle counter"))
        return "A cramped noodle counter — a few stools, a steaming pot, and a cook who doesn't look up. The smell is the best thing in the district. The corridor is back east.";
    if (n.includes("dim corridor"))
        return DIM_CORRIDOR;
    if (n.includes("narrow passage"))
        return NARROW_PASSAGE;
    if (n.includes("junction"))
        return JUNCTION;
    return DIM_CORRIDOR;
}
// --- The TravelTube stop (state-aware pod prompt, carries the reader). -------
function stopDescription(s) {
    return ("The Lower Commercial District's TravelTube stop — a single dim platform, a " +
        "long way and several lighting budgets removed from the bright stops up on " +
        "the main concourse. A reader is set into the wall. " +
        (s.flags["pod_summoned_at"] === "lcd_tube_stop"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        " A passage leads down into the district, south.");
}
const built = buildAreaFromYaml(LOWER_COMMERCIAL_YAML, {
    defaultDescription: lowerCommercialDefault,
    rooms: {
        lcd_tube_stop: {
            description: stopDescription,
            items: ["reader_lcd"],
        },
        lcd_concourse: {
            description: "The heart of the Lower Commercial District, such as it is: a low, dim " +
                "open space where the district's passages converge. After the bright, " +
                "busy main concourse this is another world — narrower, darker, and full " +
                "of businesses that prefer a quieter class of custom. The 'Tube stop is " +
                "back north; passages branch off south, east and west into the warren. " +
                "A scuffed directory board is bolted to the wall by the 'Tube passage.",
            scenery: {
                directory: LCD_DIRECTORY,
                board: LCD_DIRECTORY,
                sign: LCD_DIRECTORY,
                map: LCD_DIRECTORY,
            },
        },
        // --- Dr Rajah's Pharmaceutical Supplies (canon) ---
        // Rajah is NOT placed here statically: the resistance thread finds her at her
        // Zone B home first (see lcd_npcs.ts), and she only relocates to this unit
        // once she's redirected the PC (FLAG_RAJAH_HOME_MET). Before that the shop is
        // shut; after, it's open (the engine adds "Dr Rajah is here." when present).
        lcd_rajah_front: {
            scenery: {
                shelves: "Shelves of medical supplies, from basic first-aid to more sophisticated devices, ordered with a practitioner's care. A pharmacy that means it.",
                devices: "Sophisticated medical devices behind glass — diagnostic kit, the kind of thing a station doctor would actually want, well beyond a corner chemist's range.",
                counter: "A counter runs across the back, clean and uncluttered, the working surface of someone who keeps her trade tidy.",
                curtain: "A beaded curtain screens off a consulting room to the north — the kind of threshold that, by law, monitoring is not permitted to cross.",
                shutter: "A part-drawn shutter and a hand-written BACK SOON card. Nothing for it but to come back when she's in.",
            },
            description: (s) => s.flags[FLAG_RAJAH_HOME_MET]
                ? "Dr Rajah's Pharmaceutical Supplies: a clean, well-maintained shopfront " +
                    "that stands out from the grime of the district around it. Shelves line " +
                    "the walls, displaying everything from basic first-aid supplies to more " +
                    "sophisticated medical devices; a counter runs across the back.\n\n" +
                    "A beaded curtain screens off a consulting room to the north. The passage " +
                    "is back south."
                : "Dr Rajah's Pharmaceutical Supplies — the one clean front in a dirty row, " +
                    "and shut: the shutter is part-drawn, the lights low, and a hand-written " +
                    "card in the window reads BACK SOON. Nothing for it but to come back when " +
                    "she's in. The passage is back south.",
        },
        lcd_rajah_back: {
            description: "Through the beaded curtain: a small, private consultation room — two " +
                "seats and a desk with a drawer, and the calm, careful order of someone " +
                "who describes herself as a medical practitioner with a sideline in " +
                "retail. The shopfront is back through the curtain, south.",
        },
        // --- Teng Vessel Brokerage (canon) ---
        lcd_teng_brokerage: {
            npcs: ["teng"],
            scenery: {
                desk: "A polished desk, conspicuously tidy for the district — the desk of a man who has nothing to hide because he's very good at hiding it elsewhere.",
                terminals: "A bank of data terminals, listings scrolling: hulls, tonnages, asking prices, the dry poetry of second-hand spaceflight.",
                screens: "Wall screens cycling through ship schematics and second-hand listings — yachts, light freighters, personal transports, each with a price that assumes you have to ask.",
                schematics: "Ship schematics turning slowly on the screens, cutaways of vessels that could, the broker would gently note, take you a very long way from here.",
                note: "A discreet note advertises viewings of stock currently berthed in the district's bays — by appointment only, discretion assured.",
            },
            description: "The Teng Vessel Brokerage — a small, surprisingly tidy office wedged " +
                "between a scrap dealer and a nutrition-supplement vendor. A polished " +
                "desk, a bank of data terminals, and wall screens cycling through ship " +
                "schematics and second-hand listings: hulls, tonnages, asking prices. A " +
                "discreet note advertises viewings of stock currently berthed in the " +
                "district's docking bays — by appointment only. The alley is back south.",
        },
        lcd_scrap_dealer: {
            scenery: {
                parts: "Bins and shelves of salvaged parts, sorted loosely and priced by weight rather than function — somebody's broken ship is somebody else's bargain.",
                cabling: "Cabling sold by the metre off big scarred drums, every gauge and vintage, none of it new and most of it fine.",
                components: "Components priced by weight, which tells you everything about the margins and the clientele. Useful, if you were fixing a ship.",
                shelves: "Sagging shelves of salvage, the archaeology of every vessel that ever limped through the district.",
            },
        },
        lcd_supplement_vendor: {
            scenery: {
                tubs: "Tubs of powders wall to wall, the labels long on promises — MASS, FOCUS, RECOVERY — and conspicuously short on specifics.",
                bars: "Pressed protein bars in loud wrappers, each one guaranteeing a transformation it has no intention of delivering.",
                powders: "Powders in every shade of artificial, scoops buried in the tubs, the whole wall faintly chalky to breathe near.",
                labels: "Labels heavy on capital letters and percentages, light on anything a regulator would recognise. Independent station, independent claims.",
            },
        },
        lcd_pawnshop: {
            scenery: {
                window: "A window full of other people's emergencies — tools, trinkets, a couple of weathered datapads, each with a small handwritten price and a quiet story you'd rather not know.",
                datapad: "An old datapad in the window, scratched and obsolete and, crucially, the sort of thing that has never been near a network and never will. You file the thought away.",
                datapads: "A couple of weathered datapads among the pledges — obsolete, off-grid, and quietly interesting to anyone who needed to read something without the network listening.",
                trinkets: "Trinkets and oddments under the glass, the small valuables people part with last and least willingly.",
                tools: "Pledged tools, good ones mostly, redeemable in theory and abandoned in practice.",
            },
        },
        lcd_noodle_counter: {
            scenery: {
                pot: "A great steaming pot of broth, the source of the best smell in the district, tended by a cook who never quite looks up from it.",
                stools: "A few mismatched stools at the counter, polished by the backsides of regulars who know to come early.",
                cook: "The cook works the pot without acknowledging you — service here is the food arriving, and nothing more. BUY some NOODLES.",
                broth: "Broth that has clearly been going for longer than some marriages, and is the better for it. BUY some NOODLES.",
            },
        },
    },
});
// Cross-area, on-foot link: a long walkway south into the Industrial Sector's
// painting chamber (the Industrial side's reciprocal north is wired in
// industrial.ts). The mapper drops cross-area exits.
built.rooms["lcd_walkway_3"].exits.south =
    { to: "horizon_painting_chamber", description: "the Industrial Sector" };
export const lowerCommercialRooms = built.rooms;
