// Service Area — a small back-of-house maintenance stub: a short service-access
// corridor and a gantry over the station's working guts, reached ONLY by
// TravelTube (no walking link to the rest of the outpost). Built from
// maps/service_area.yaml via buildAreaFromYaml. The 'Tube stop
// (horizon_service_access_corridor) is declared in its index.ts MODULES entry,
// with its reader item (reader_service).
import { buildAreaFromYaml } from "./area.js";
const SERVICE_AREA_YAML = `
# Generated by tools/mapper.html
area: service_area
areaName: "Service Area"
stop: horizon_service_access_corridor
rooms:
  - id: horizon_service_access_corridor
    name: "Service access corridor"
    stop: true
    exits:
      east: service_access_corridor2
  - id: service_access_corridor2
    name: "Service access corridor"
    exits:
      north: service_access_corridor3
      west: horizon_service_access_corridor
  - id: service_access_corridor3
    name: "Service access corridor"
    exits:
      north: horizon_service_access_gantry
      south: service_access_corridor2
  - id: horizon_service_access_gantry
    name: "Service access gantry"
    exits:
      south: service_access_corridor3
`;
const CORRIDOR = "A bare service-access corridor — exposed conduit bundled along the ceiling, " +
    "stencilled hazard striping underfoot, and the unfinished, functional feel of " +
    "the back-of-house spaces the public never normally sees. It runs on, plainly, " +
    "in either direction.";
const GANTRY = "A metal service gantry — purely industrial in purpose, grated floors and " +
    "metal railings stretching out in a lattice of levels. But the gantry itself " +
    "is almost beside the point.\n\n" +
    "The outer hull of the station curves away before you, and embedded in it are " +
    "great transparent hexagons — a hundred or more windows onto space. Through " +
    "them, stars blaze in dense clusters against an inky void, sharp and vivid; " +
    "wisps of nebulae unfurl in ribbons of violet and green, mingling with the " +
    "faint blush of stardust. The shadowed curve of the orbited planet dominates " +
    "part of the view, its surface a subtle blend of blues and browns, enormous " +
    "and close. Dozens of spacecraft drift in the middle distance — some sleek " +
    "and arrowlike, others boxy and industrial, a few bristling with antennae — " +
    "while small autonomous shuttles dart between them like busy insects, tracing " +
    "their ceaseless, mesmerising dance.\n\n" +
    "It is quiet here. Tucked away from the milieu of the busier parts of the " +
    "outpost, this is a place to think, to breathe, and to feel, for a moment, " +
    "the full scale of everything beyond these walls. Someone who knew this place " +
    "would not give it up lightly.\n\n" +
    "The corridor is back through the double doors, south.";
// The corridor segment between the 'Tube stop and the gantry approach: like the
// rest of the back-of-house run, but with one odd, oddly-smooth deck-plate that
// looks as though it might be slippery (canon — a foreshadowed hazard).
const CORRIDOR_SLIPPERY = "A bare service-access corridor — exposed conduit bundled along the ceiling, " +
    "stencilled hazard striping underfoot, and the unfinished, functional feel of " +
    "the back-of-house spaces the public never normally sees. One deck-plate sits " +
    "slightly proud of the rest, its surface oddly smooth and worn — it looks as " +
    "though it might be slippery. The corridor runs on, plainly, in either " +
    "direction.";
// The corridor segment that meets the gantry: a pair of heavy double doors
// (described, non-functional — they slide open automatically) stand at its
// north end.
const CORRIDOR_TO_GANTRY = "A bare service-access corridor — exposed conduit bundled along the ceiling, " +
    "stencilled hazard striping underfoot. At its north end stands a pair of " +
    "heavy double doors; they slide apart automatically as you approach, " +
    "revealing the gantry beyond. The corridor runs back south.";
function serviceDefault(r) {
    if (r.name.toLowerCase().includes("gantry"))
        return GANTRY;
    return CORRIDOR;
}
// The corridor segment that holds the 'Tube stop gets the state-aware pod prompt
// and carries the reader item.
function stopDescription(s) {
    return ("The mouth of the service area: a back-of-house access corridor with the " +
        "stripped-down, functional look of somewhere not meant for visitors — clean, " +
        "with a faint air of disuse, though the filtered air carries none of the " +
        "mustiness you'd expect of a place so seldom visited. A " +
        "TravelTube stop is set into the wall — the only way in or out. " +
        (s.flags["pod_summoned_at"] === "horizon_service_access_corridor"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        " The corridor runs on east.");
}
const built = buildAreaFromYaml(SERVICE_AREA_YAML, {
    defaultDescription: serviceDefault,
    rooms: {
        horizon_service_access_corridor: {
            description: stopDescription,
            items: ["reader_service"],
        },
        service_access_corridor2: {
            description: CORRIDOR_SLIPPERY,
        },
        service_access_corridor3: {
            description: CORRIDOR_TO_GANTRY,
        },
    },
});
export const serviceRooms = built.rooms;
