// Flight Training Area — Horizon Outpost's pilot school. Two levels joined ONLY
// by a lift (the engine's multi-level model — cf. Residential Zone B, Donovan's):
//   Level 1 = classroom level: the TravelTube exit corridor (signpost wall), a
//     main corridor that splits into two classroom wings (1-3 left, 4-6 right),
//     the toilets, and the lift.
//   Level 2 = the Simulator Deck (pod simulators) + the Break Room off it.
//
// Built from maps/flight_training.yaml via buildAreaFromYaml; the lift is
// registered with liftDefFromYaml/withLiftDirs (base id training_lift). Reached
// by TravelTube only (training_tube_stop, declared in its index.ts MODULES entry
// with reader_training). Descriptions are canon-informed placeholder/starter
// prose — Hale, the ID-gated classroom doors, and the simulator exercises are
// content for a later pass.
import { buildAreaFromYaml } from "./area.js";
import { withLiftDirs, liftDefFromYaml, liftDescription } from "./lifts.js";
const FLIGHT_TRAINING_YAML = `
# Generated by tools/mapper.html
area: flight_training
areaName: "Flight Training Area"
stop: training_tube_stop
levels: 2
lift: training_lift
rooms:
  - id: training_tube_stop
    level: 1
    name: "Flight Training — TravelTube Exit Corridor"
    stop: true
    exits:
      east: training_main_corridor
      south: training_toilets
  - id: training_toilets
    level: 1
    name: "Flight Training — Toilets"
    exits:
      north: training_tube_stop
  - id: training_main_corridor
    level: 1
    name: "Flight Training — Main Corridor"
    exits:
      west: training_tube_stop
      north: training_classwing_left1
      south: training_classwing_right1
      east: training_lift_l1
  - id: training_lift_l1
    level: 1
    name: "Flight Training — Lift"
    lift: true
    exits:
      west: training_main_corridor
  - id: training_classwing_left1
    level: 1
    name: "Flight Training — Classroom Wing (1-3)"
    exits:
      south: training_main_corridor
      north: training_classwing_left2
      west: training_anon_door
      east: training_classroom_3
  - id: training_classwing_left2
    level: 1
    name: "Flight Training — Classroom Wing (1-3)"
    exits:
      south: training_classwing_left1
      north: training_classwing_left3
      east: training_classroom_2
  - id: training_classwing_left3
    level: 1
    name: "Flight Training — Classroom Wing (1-3)"
    exits:
      south: training_classwing_left2
      east: training_classroom_1
  - id: training_anon_door
    level: 1
    name: "Flight Training — Unmarked Door"
    exits:
      east: training_classwing_left1
  - id: training_classroom_1
    level: 1
    name: "Flight Training — Classroom 1"
    exits:
      west: training_classwing_left3
  - id: training_classroom_2
    level: 1
    name: "Flight Training — Classroom 2"
    exits:
      west: training_classwing_left2
  - id: training_classroom_3
    level: 1
    name: "Flight Training — Classroom 3"
    exits:
      west: training_classwing_left1
  - id: training_classwing_right1
    level: 1
    name: "Flight Training — Classroom Wing (4-6)"
    exits:
      north: training_main_corridor
      south: training_classwing_right2
      east: training_classroom_4
  - id: training_classwing_right2
    level: 1
    name: "Flight Training — Classroom Wing (4-6)"
    exits:
      north: training_classwing_right1
      south: training_classwing_right3
      east: training_classroom_5
  - id: training_classwing_right3
    level: 1
    name: "Flight Training — Classroom Wing (4-6)"
    exits:
      north: training_classwing_right2
      east: training_classroom_6
  - id: training_classroom_4
    level: 1
    name: "Flight Training — Classroom 4"
    exits:
      west: training_classwing_right1
  - id: training_classroom_5
    level: 1
    name: "Flight Training — Classroom 5"
    exits:
      west: training_classwing_right2
  - id: training_classroom_6
    level: 1
    name: "Flight Training — Classroom 6"
    exits:
      west: training_classwing_right3
  - id: training_lift_l2
    level: 2
    name: "Flight Training — Lift"
    lift: true
    exits:
      south: training_sim_deck
  - id: training_sim_deck
    level: 2
    name: "Flight Training — Simulator Deck"
    exits:
      north: training_lift_l2
      east: training_break_room
  - id: training_break_room
    level: 2
    name: "Flight Training — Break Room"
    exits:
      west: training_sim_deck
`;
// --- Generic, by-kind prose -------------------------------------------------
const CLASS_CORRIDOR = "A clean training-wing corridor — the same cream walls and dark-grey floor as " +
    "the rest of the area. Classroom doors open off it at intervals, each with an " +
    "ID reader on the wall beside it. The wing runs on.";
const CLASSROOM = "A standard training classroom: rows of desks, each with a chair and a " +
    "terminal, all facing a large screen at the front and the instructor's desk " +
    "before it. Empty just now. The corridor is back west.";
function trainingDefault(r) {
    if (r.id.startsWith("training_lift_l"))
        return liftDescription;
    const n = r.name.toLowerCase();
    if (n.includes("classroom wing"))
        return CLASS_CORRIDOR;
    if (n.includes("classroom"))
        return CLASSROOM;
    return CLASS_CORRIDOR;
}
// --- The TravelTube stop (state-aware pod prompt, carries the reader). -------
function stopDescription(s) {
    return ("You emerge into a nondescript corridor — plain cream-coloured walls, a dark " +
        "grey floor, spotlessly clean, like most frequented parts of the outpost. " +
        "Directly opposite the travel-tube exit, signs on the wall point the way to " +
        "Classrooms 1 to 6, the Simulator Deck, the Break Room, and the Toilets. " +
        (s.flags["pod_summoned_at"] === "training_tube_stop"
            ? "A pod waits in the bay, doors open — you can BOARD it."
            : "Scan your ID at the reader to summon a pod.") +
        "\n\nTurning right, the corridor runs on east toward the classroom wings and " +
        "the lift; the toilets are off to the south.");
}
const built = buildAreaFromYaml(FLIGHT_TRAINING_YAML, {
    defaultDescription: trainingDefault,
    rooms: {
        training_tube_stop: {
            description: stopDescription,
            items: ["reader_training"],
        },
        training_main_corridor: {
            description: "A short stretch of corridor that splits just ahead. Signs confirm the " +
                "layout: Classrooms 1–3 to the left (north), Classrooms 4–6 to the right " +
                "(south). Straight on to the east, a lift serves the Simulator Deck and " +
                "the Break Room. The travel-tube exit is back west.",
        },
        training_toilets: {
            description: "A clean public toilet block, the same spotless cream-and-grey as the " +
                "corridor outside. The corridor is back north.",
        },
        // Canon interior (Classroom 2 is the one described in the text).
        training_classroom_2: {
            description: "Classroom 2. Five rows of four desks — twenty student stations in all, " +
                "each with a chair and a terminal. A large screen dominates the front " +
                "wall, with a substantial instructor's desk and terminal set before it, " +
                "facing the room. The entrance is to the side. The corridor is back west.",
        },
        // The anonymous unlabelled door (purpose unconfirmed in canon — inferred).
        training_anon_door: {
            description: "Behind the unmarked door — no sign, no ID reader — is a cramped, dim " +
                "utility space: fuse panels, cleaning supplies, a mop sink. Nothing to " +
                "explain why it sits unlabelled among the classrooms. The corridor is " +
                "back east.",
        },
        training_sim_deck: {
            description: "The Simulator Deck — a deck of its own, given over to flight " +
                "simulation. Pod-like simulator enclosures stand in ranks across the " +
                "floor, each big enough to climb into and strap down in; an instructor " +
                "can watch from a portable screen or the large external display on the " +
                "wall. The lift is back north; the break room opens east.",
        },
        training_break_room: {
            description: "A utilitarian break room where the class decamps between simulator " +
                "sessions and for lunch — a few tables, a drinks station, and a terminal " +
                "in the corner. The simulator deck is back west.",
        },
    },
});
// The 2-level lift; registered via the training MODULES entry (index.ts).
export const trainingLift = withLiftDirs(liftDefFromYaml(built.parsed, {
    1: { label: "Classroom Level", names: ["1", "classroom", "classrooms", "classroom level", "ground", "lower", "down"] },
    2: { label: "Simulator Deck", names: ["2", "sim", "simulator", "simulator deck", "sim deck", "break room", "break", "upper", "up"] },
}), built.rooms);
export const trainingRooms = built.rooms;
